server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: syspass1234
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB
