server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: syspass1234
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB

---
app:
  token:
    secret: 49614285-181f-436d-b77c-724c200a31ab
    issuer: BankenService
